from abc import ABC, abstractmethod
from .models import Document, RAGQuery
from typing import List, Dict, Any, Optional

class IngestionBase(ABC):
    @abstractmethod
    async def ingest(self, **kwargs) -> List[Document]: ...

class VectorStoreBase(ABC):
    @abstractmethod
    async def add_documents(self, documents: List[Document]): ...
    @abstractmethod
    async def search(self, query: str, k: int = 5) -> List[Document]: ...

class KnowledgeGraphBase(ABC):
    @abstractmethod
    async def add_document(self, document: Document): ...
    @abstractmethod
    async def query_relations(self, query: str) -> List[Dict[str, Any]]: ...

class MemoryBase(ABC):
    @abstractmethod
    async def add_context(self, query: RAGQuery, response: str): ...
    @abstractmethod
    async def get_context(self, query: str) -> str: ...

class TextIndexBase(ABC):
    @abstractmethod
    async def add_documents(self, documents: List[Document]) -> None: ...
    @abstractmethod
    async def search(self, query: str, k: int = 10, filters: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def delete_documents(self, doc_ids: List[str]) -> None: ...
    @abstractmethod
    async def health_check(self) -> bool: ...

class LLMBase(ABC):
    @abstractmethod
    def invoke(self, prompt: str) -> Any: ... 